library(readr)
ev <- read_csv("data/processed/internacoes_evitadas.csv", show_col_types=FALSE)
cat("=== COLUNAS ===\n")
print(names(ev))
cat("\n=== TAIL (10 linhas) ===\n")
cols <- intersect(c("data","evitadas_mes","evitadas_acum","custo_mes_central","custo_acum_central"), names(ev))
print(tail(ev[, cols], 10))
cat("\n=== POST-INTERV (primeiras 5) ===\n")
pos <- ev[!is.na(ev$taxa_cf), ]
print(pos[1:5, cols])
cat("\n=== evitadas_mes eh crescente? (diff) ===\n")
cat("range diff:", range(diff(ev$evitadas_mes[!is.na(ev$evitadas_mes)])), "\n")
cat("primeiros vals pos:", head(pos$evitadas_mes, 8), "\n")
cat("evitadas_acum:", head(pos$evitadas_acum, 8), "\n")
